name: Publish Python distributions to PyPI and TestPyPI

on:
  push:
    branches: [ master, main ]
    
    # Don't trigger if it's just a documentation update
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '**.yml'
      - '**.sh'
      - 'docs/**'
      - 'Dockerfile'
      - 'LICENSE'
      - '.gitattributes'
      - '.gitignore'
      - '.dockerignore'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Initialize Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
        cache: 'pip'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build Dist
      run: |
        python setup.py sdist
    - name: Release On Main PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.MAIN_PYPI }}
        skip_existing: true
        verbose: true
        print_hash: true